#!/bin/bash
# unattended idempotent password generator
[ $UID -ne 0 ] && exit 1
export PATH="/var/lib/gems/1.8/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export SECRET_NAME=$1

# running secret and root-secret will be functionally equivalent after the first run
[ -z "${SECRET_NAME}" ] && export SECRET_NAME="$(hostname -s)"

export COMMAND="secret-${SECRET_NAME}"

# run the command or create it
${COMMAND} 2>/dev/null || \
  (
    umask 0077;
    echo -e '#!/bin/bash\n'"echo -n \"$(dd if=/dev/urandom bs=16 count=1 2>/dev/null|sha1sum|cut -b 1-40)\"" \
      > /usr/local/sbin/${COMMAND};
    # because umask doesn't always...
    chmod 700 /usr/local/sbin/${COMMAND};
    # now get what we created
    ${COMMAND}
  )
