#!/bin/bash
BASEDN=$(grep "^olcSuffix: " /etc/ldap/slapd.d/cn\=config/olcDatabase\=\{1\}hdb.ldif|sed -e 's/^olcSuffix: //')
LDAPDOMAIN=$(echo "${BASEDN}" | sed -e 's/,dc=/./g' -e 's/dc=//')
export BASEDN LDAPDOMAIN
ldapsearch -LLLxH ldap://127.0.0.1:389 \
           -b "${BASEDN}" \
           -D "cn=admin,${BASEDN}" \
           -w "$(secret ${LDAPDOMAIN})" \
           > /dev/null
EXIT=$?
if [ $EXIT -ne 0 ];then
  /usr/sbin/service slapd stop
  sed -i -e "s/olcRootPW:: .*/olcRootPW:: $(slappasswd -s $(secret ${LDAPDOMAIN}) | base64)/" \
    /etc/ldap/slapd.d/cn\=config/olcDatabase\=\{1\}hdb.ldif
  /usr/sbin/service slapd start
  ldapsearch -LLLxH ldap://127.0.0.1:389 \
             -b "${BASEDN}" \
             -D "cn=admin,${BASEDN}" \
             -w "$(secret ${LDAPDOMAIN})" \
             > /dev/null
  exit $?
fi
